### ISSUE TITLE
Not drawing BMP images from URL correctly.

### ISSUE THREAD

**Issue by chrisjtwomey** [SolderedElectronics/Inkplate-Arduino-library#161] opened 2022-10-08 11:08 UTC
I have this piece of code:

```
display.begin();
display.clearDisplay();
display.display();

if (!display.drawImage(url, 0, 0, false, false)) {
    display.println("Image open error");
}
display.display();
```

When `url = "http://192.168.1.11:/homepage.png"`, Inkplate10 display draws image as I'd expect:

<img src="https://user-images.githubusercontent.com/5797356/194703515-2952a504-2969-4df5-8863-530a8e25ca81.jpg" width="450">

When `url = "http://192.168.1.11:/homepage.bmp"`, the image drawn is almost completely black:

<img src="https://user-images.githubusercontent.com/5797356/194703725-e04cfd42-25d8-4195-a97d-ad5cf53bb519.jpg" width="450">

I thought maybe there was some funny business happening with how Inkplate is interpreting the background but inverting the image doesn't seem to make much of a difference:

<img src="https://user-images.githubusercontent.com/5797356/194703733-d5283389-fe9d-41c1-8b83-b03fcc1d92ac.jpg" width="450">

I've attached both the png and bmp images I've been testing with below if anyone else wants to try them:
[homepage.zip](https://github.com/e-radionicacom/Inkplate-Arduino-library/files/9739028/homepage.zip)

What's interesting is that trying the same files with a Waveshare board using GXEPD2, I get behaviour similar to PNG here. In the end, I've gotten around this by just using PNG, but still interested in the cause of this.

**Comment by KarloLeksic** [comment] 2023-04-15 08:31
Hi,

Try updating the Inkplate library to the latest and also the board definition. If that doesn't solve the problem, maybe the problem is in the color palette. Convert the image to 24-bit bmp as that seems to work best.

**Comment by rspurlock** [comment] 2023-05-06 05:28
I believe the pull request titled "Add missing default arguments and fix 1-bit BMP draw image from buffer" will fix this BMP display issue as that was the problem I was having trying to draw monochrome (1-bit) BMP images.

**Comment by rsoric** [comment] 2024-03-25 11:01
Closing this as there's no more activity, please reopen the issue if you think it needs more attention

**Closed by rsoric** 2024-03-25 11:01 UTC
